### ISSUE TITLE
False positive (error) using brackets in title

### ISSUE THREAD

**Issue by Gr3q** [kontrolplane/pull-request-title-validator#9]
```yaml
name: validate-pull-request-title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  validator:
    name: validate-pull-request-title
    runs-on: ubuntu-latest
    steps:
      - name: validate pull request title
        uses: kontrolplane/pull-request-title-validator@v1.3.2
        with:
          types: "fix,feat,chore,docs,build,ci,refactor,perf,test,WIP"
```

PR title:

`fix: Dialogs (and Setup finished animation) are missing`

Output:

```
no custom list of commit scopes was passed using fallback.
The type passed 'fix: Dialogs ' is not present in the types allowed by the convention: [fix feat chore docs build ci refactor perf test WIP]
```
